name: Ubuntu RDP

on:
  workflow_dispatch:
    inputs:
      hostname:
        description: 'Enter Hostname:'
        required: true
        default: Ubunturdp
        type: string
      username:
        description: 'Enter Username:'
        required: true
        default: guest
        type: string
      password:
        description: 'Enter Password:'
        required: true
        default: 1111
        type: string
      Pin:
        description: 'Enter a Pin (more or equal to 6 digits)'
        required: true
        default: 1234567890
        type: number
      CRP:
        description: 'Visit at http://remotedesktop.google.com/headless and, copy the command after authentication'
        required: true
        type: string

env:
  hostname: ${{ Ubunturdp }}
  username: ${{ guest }}
  password: ${{ 1111 }}
  Pin: ${{ 1234567890 }}
  CRP: ${{ DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0AeaYSHCYpAhl_YgRSjO9ECkhG4E50CB1EX97eEPH93IpwMDnFtXI9QDcO1A8Poqx0CGnjA" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname) }}

jobs:
  build:
    name: Launch Ubuntu RDP Server
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Cleanup Junk
        run: |
          mkdir Cleanup_Script
          cd Cleanup_Script
          curl -L -o cleanup-storage-of-runneros.sh \
              https://raw.githubusercontent.com/rokibhasansagar/slimhub_actions/main/cleanup.sh
          chmod +x cleanup-storage-of-runneros.sh
          ./cleanup-storage-of-runneros.sh
 
      - name: Create Ubuntu RDP Server
        run: |
          mkdir Create_Server
          cd Create_Server
          curl -L -o create-ubuntu-rdp-server.sh \
              https://raw.githubusercontent.com/Diwash0007/Ubuntu_RDP/main/Ubuntu_RDP.sh
          chmod +x create-ubuntu-rdp-server.sh
          ./create-ubuntu-rdp-server.sh

      - name: Keep Running
        run: |
          mkdir Keep_Running
          cd Keep_Running
          curl -L -o keep-ubuntu-rdp-server-running.sh \
              https://raw.githubusercontent.com/Diwash0007/Ubuntu_RDP/main/Keep_Running.sh
          chmod +x keep-ubuntu-rdp-server-running.sh
          ./keep-ubuntu-rdp-server-running.sh
